# Generated by Django 5.0.2 on 2025-02-02 10:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the question in English')),
                ('answer', ckeditor.fields.RichTextField(help_text='Format your answer using the editor')),
                ('question_hi', models.TextField(blank=True, verbose_name='Question (Hindi)')),
                ('question_bn', models.TextField(blank=True, verbose_name='Question (Bengali)')),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, verbose_name='Answer (Hindi)')),
                ('answer_bn', ckeditor.fields.RichTextField(blank=True, verbose_name='Answer (Bengali)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
